import 'package:flutter/material.dart';
import 'package:flutterapp/boardgamesapp/generatedreviewwidget/generated/GeneratedMaskGroupWidget6.dart';
import 'package:flutterapp/boardgamesapp/generatedreviewwidget/generated/GeneratedMaskGroupWidget8.dart';
import 'package:flutterapp/boardgamesapp/generatedreviewwidget/generated/GeneratedNombrejuegoWidget9.dart';
import 'package:flutterapp/boardgamesapp/generatedreviewwidget/generated/GeneratedMaskGroupWidget5.dart';
import 'package:flutterapp/boardgamesapp/generatedreviewwidget/generated/GeneratedRectangle4Widget5.dart';
import 'package:flutterapp/boardgamesapp/generatedreviewwidget/generated/GeneratedMaskGroupWidget9.dart';
import 'package:flutterapp/boardgamesapp/generatedreviewwidget/generated/GeneratedMaskGroupWidget12.dart';
import 'package:flutterapp/boardgamesapp/generatedreviewwidget/generated/GeneratedMaskGroupWidget7.dart';
import 'package:flutterapp/boardgamesapp/generatedreviewwidget/generated/GeneratedMaskGroupWidget4.dart';
import 'package:flutterapp/boardgamesapp/generatedreviewwidget/generated/GeneratedMaskGroupWidget10.dart';
import 'package:flutterapp/boardgamesapp/generatedreviewwidget/generated/GeneratedMaskGroupWidget11.dart';

/* Frame Review
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedReviewWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 40, 34, 34),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 31.0,
                child: GeneratedRectangle4Widget5(),
              ),
              Positioned(
                left: 27.0,
                top: 124.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 212.0,
                child: GeneratedMaskGroupWidget4(),
              ),
              Positioned(
                left: 60.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 80.0,
                child: GeneratedMaskGroupWidget5(),
              ),
              Positioned(
                left: 236.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 80.0,
                child: GeneratedMaskGroupWidget6(),
              ),
              Positioned(
                left: 57.0,
                top: 538.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 80.0,
                child: GeneratedMaskGroupWidget7(),
              ),
              Positioned(
                left: 145.0,
                top: 538.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 80.0,
                child: GeneratedMaskGroupWidget8(),
              ),
              Positioned(
                left: 57.0,
                top: 354.0,
                right: null,
                bottom: null,
                width: 258.0,
                height: 50.0,
                child: GeneratedMaskGroupWidget9(),
              ),
              Positioned(
                left: 41.0,
                top: 681.0,
                right: null,
                bottom: null,
                width: 135.0,
                height: 44.0,
                child: GeneratedMaskGroupWidget10(),
              ),
              Positioned(
                left: 199.0,
                top: 681.0,
                right: null,
                bottom: null,
                width: 135.0,
                height: 44.0,
                child: GeneratedMaskGroupWidget11(),
              ),
              Positioned(
                left: 31.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 201.0,
                height: 26.0,
                child: GeneratedNombrejuegoWidget9(),
              ),
              Positioned(
                left: 148.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 80.0,
                child: GeneratedMaskGroupWidget12(),
              )
            ]),
      ),
    ));
  }
}
