import 'package:flutter/material.dart';
import 'package:flutterapp/boardgamesapp/generatednotificationswidget1/generated/GeneratedRectangle4Widget4.dart';
import 'package:flutterapp/boardgamesapp/generatednotificationswidget1/generated/GeneratedImagen_20210118_1634501Widget2.dart';
import 'package:flutterapp/boardgamesapp/generatednotificationswidget1/generated/GeneratedMaskGroupWidget.dart';
import 'package:flutterapp/boardgamesapp/generatednotificationswidget1/generated/GeneratedBell1Widget2.dart';
import 'package:flutterapp/boardgamesapp/generatednotificationswidget1/generated/GeneratedUser1Widget2.dart';
import 'package:flutterapp/boardgamesapp/generatednotificationswidget1/generated/GeneratedMaskGroupWidget2.dart';
import 'package:flutterapp/boardgamesapp/generatednotificationswidget1/generated/GeneratedLine1Widget2.dart';
import 'package:flutterapp/boardgamesapp/generatednotificationswidget1/generated/GeneratedMaskGroupWidget3.dart';
import 'package:flutterapp/boardgamesapp/generatednotificationswidget1/generated/GeneratedMaskGroupWidget1.dart';
import 'package:flutterapp/boardgamesapp/generatednotificationswidget1/generated/GeneratedHouse1Widget2.dart';

/* Frame Notifications
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNotificationsWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 40, 34, 34),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 31.0,
                child: GeneratedRectangle4Widget4(),
              ),
              Positioned(
                left: 17.0,
                top: 49.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 92.0,
                child: GeneratedMaskGroupWidget(),
              ),
              Positioned(
                left: 17.0,
                top: 151.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 92.0,
                child: GeneratedMaskGroupWidget1(),
              ),
              Positioned(
                left: 17.0,
                top: 253.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 92.0,
                child: GeneratedMaskGroupWidget2(),
              ),
              Positioned(
                left: 17.0,
                top: 355.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 92.0,
                child: GeneratedMaskGroupWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 740.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedLine1Widget2(),
              ),
              Positioned(
                left: 304.0,
                top: 757.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedImagen_20210118_1634501Widget2(),
              ),
              Positioned(
                left: 122.0,
                top: 757.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedBell1Widget2(),
              ),
              Positioned(
                left: 213.0,
                top: 757.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedUser1Widget2(),
              ),
              Positioned(
                left: 31.0,
                top: 757.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedHouse1Widget2(),
              )
            ]),
      ),
    ));
  }
}
