import 'package:flutter/material.dart';
import 'package:flutterapp/boardgamesapp/generatedopcionswidget/generated/GeneratedTableroWidget.dart';
import 'package:flutterapp/boardgamesapp/generatedopcionswidget/generated/GeneratedRectangle4Widget1.dart';
import 'package:flutterapp/boardgamesapp/generatedopcionswidget/generated/GeneratedCategoriesWidget.dart';
import 'package:flutterapp/boardgamesapp/generatedopcionswidget/generated/GeneratedDadosWidget.dart';
import 'package:flutterapp/boardgamesapp/generatedopcionswidget/generated/GeneratedRolWidget.dart';
import 'package:flutterapp/boardgamesapp/generatedopcionswidget/generated/GeneratedCartasWidget.dart';
import 'package:flutterapp/boardgamesapp/generatedopcionswidget/generated/GeneratedFichasWidget.dart';
import 'package:flutterapp/boardgamesapp/generatedopcionswidget/generated/GeneratedLine5Widget1.dart';
import 'package:flutterapp/boardgamesapp/generatedopcionswidget/generated/GeneratedRectangle6Widget.dart';

/* Frame Opcions
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOpcionsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedPaginaPrincipalWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 812.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 40, 34, 34),
                  ),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 31.0,
                  child: GeneratedRectangle4Widget1(),
                ),
                Positioned(
                  left: 0.0,
                  top: 29.0,
                  right: null,
                  bottom: null,
                  width: 302.0,
                  height: 781.0,
                  child: GeneratedRectangle6Widget(),
                ),
                Positioned(
                  left: 19.0,
                  top: 418.0,
                  right: null,
                  bottom: null,
                  width: 122.0,
                  height: 33.0,
                  child: GeneratedTableroWidget(),
                ),
                Positioned(
                  left: -2.384185791015625e-7,
                  top: 31.0,
                  right: null,
                  bottom: null,
                  width: 302.0,
                  height: 779.0,
                  child: GeneratedLine5Widget1(),
                ),
                Positioned(
                  left: 19.0,
                  top: 51.0,
                  right: null,
                  bottom: null,
                  width: 160.0,
                  height: 60.0,
                  child: GeneratedCategoriesWidget(),
                ),
                Positioned(
                  left: 20.0,
                  top: 139.0,
                  right: null,
                  bottom: null,
                  width: 122.0,
                  height: 33.0,
                  child: GeneratedDadosWidget(),
                ),
                Positioned(
                  left: 19.0,
                  top: 214.0,
                  right: null,
                  bottom: null,
                  width: 122.0,
                  height: 33.0,
                  child: GeneratedFichasWidget(),
                ),
                Positioned(
                  left: 19.0,
                  top: 278.0,
                  right: null,
                  bottom: null,
                  width: 122.0,
                  height: 33.0,
                  child: GeneratedCartasWidget(),
                ),
                Positioned(
                  left: 19.0,
                  top: 350.0,
                  right: null,
                  bottom: null,
                  width: 122.0,
                  height: 33.0,
                  child: GeneratedRolWidget(),
                )
              ]),
        ),
      ),
    ));
  }
}
