import 'package:flutter/material.dart';
import 'package:flutterapp/boardgamesapp/generatedgamewidget/generated/GeneratedKeepyourbodysafefromviruseswhileinfectingyourrivalsWidg.dart';
import 'package:flutterapp/boardgamesapp/generatedgamewidget/generated/GeneratedBell1Widget3.dart';
import 'package:flutterapp/boardgamesapp/generatedgamewidget/generated/GeneratedLine1Widget3.dart';
import 'package:flutterapp/boardgamesapp/generatedgamewidget/generated/Generated26PlayersWidget.dart';
import 'package:flutterapp/boardgamesapp/generatedgamewidget/generated/GeneratedRectangle4Widget8.dart';
import 'package:flutterapp/boardgamesapp/generatedgamewidget/generated/GeneratedLine2Widget1.dart';
import 'package:flutterapp/boardgamesapp/generatedgamewidget/generated/Generated20minPlayingtimeWidget.dart';
import 'package:flutterapp/boardgamesapp/generatedgamewidget/generated/GeneratedMaskGroupWidget22.dart';
import 'package:flutterapp/boardgamesapp/generatedgamewidget/generated/GeneratedAge8Widget.dart';
import 'package:flutterapp/boardgamesapp/generatedgamewidget/generated/GeneratedLine3Widget1.dart';
import 'package:flutterapp/boardgamesapp/generatedgamewidget/generated/GeneratedVirus2015Widget.dart';
import 'package:flutterapp/boardgamesapp/generatedgamewidget/generated/Generated91kEcK6BaL1Widget.dart';
import 'package:flutterapp/boardgamesapp/generatedgamewidget/generated/GeneratedHouse1Widget3.dart';
import 'package:flutterapp/boardgamesapp/generatedgamewidget/generated/GeneratedUser1Widget3.dart';
import 'package:flutterapp/boardgamesapp/generatedgamewidget/generated/GeneratedImagen_20210118_1634501Widget3.dart';
import 'package:flutterapp/boardgamesapp/generatedgamewidget/generated/GeneratedMaskGroupWidget21.dart';
import 'package:flutterapp/boardgamesapp/generatedgamewidget/generated/GeneratedNombreusuarioWidget.dart';
import 'package:flutterapp/boardgamesapp/generatedgamewidget/generated/GeneratedLine4Widget2.dart';
import 'package:flutterapp/boardgamesapp/generatedgamewidget/generated/Generated450_10001Widget.dart';

/* Frame Game
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGameWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 40, 34, 34),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 31.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 121.0,
                child: Generated91kEcK6BaL1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 31.0,
                child: GeneratedRectangle4Widget8(),
              ),
              Positioned(
                left: 0.0,
                top: 740.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedLine1Widget3(),
              ),
              Positioned(
                left: 31.0,
                top: 290.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 1.0,
                child: GeneratedLine2Widget1(),
              ),
              Positioned(
                left: 145.0,
                top: 290.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 1.0,
                child: GeneratedLine3Widget1(),
              ),
              Positioned(
                left: 246.0,
                top: 290.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 1.0,
                child: GeneratedLine4Widget2(),
              ),
              Positioned(
                left: 304.0,
                top: 757.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedImagen_20210118_1634501Widget3(),
              ),
              Positioned(
                left: 122.0,
                top: 757.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedBell1Widget3(),
              ),
              Positioned(
                left: 213.0,
                top: 757.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedUser1Widget3(),
              ),
              Positioned(
                left: 31.0,
                top: 757.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedHouse1Widget3(),
              ),
              Positioned(
                left: 23.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 221.0,
                height: 54.0,
                child: GeneratedVirus2015Widget(),
              ),
              Positioned(
                left: 23.0,
                top: 225.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 50.0,
                child:
                    GeneratedKeepyourbodysafefromviruseswhileinfectingyourrivalsWidg(),
              ),
              Positioned(
                left: 44.0,
                top: 290.0,
                right: null,
                bottom: null,
                width: 103.0,
                height: 43.0,
                child: Generated26PlayersWidget(),
              ),
              Positioned(
                left: 269.0,
                top: 294.0,
                right: null,
                bottom: null,
                width: 103.0,
                height: 43.0,
                child: GeneratedAge8Widget(),
              ),
              Positioned(
                left: 23.0,
                top: 349.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 118.0,
                child: Generated450_10001Widget(),
              ),
              Positioned(
                left: 167.0,
                top: 294.0,
                right: null,
                bottom: null,
                width: 103.0,
                height: 43.0,
                child: Generated20minPlayingtimeWidget(),
              ),
              Positioned(
                left: 23.0,
                top: 501.0,
                right: null,
                bottom: null,
                width: 156.0,
                height: 42.0,
                child: GeneratedMaskGroupWidget21(),
              ),
              Positioned(
                left: 23.0,
                top: 558.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 168.0,
                child: GeneratedMaskGroupWidget22(),
              ),
              Positioned(
                left: 130.0,
                top: 582.0,
                right: null,
                bottom: null,
                width: 109.0,
                height: 23.0,
                child: GeneratedNombreusuarioWidget(),
              )
            ]),
      ),
    ));
  }
}
