import 'package:flutter/material.dart';
import 'package:flutterapp/boardgamesapp/generatedsearchwidget/generated/GeneratedMaskGroupWidget19.dart';
import 'package:flutterapp/boardgamesapp/generatedsearchwidget/generated/GeneratedRectangle4Widget7.dart';
import 'package:flutterapp/boardgamesapp/generatedsearchwidget/generated/GeneratedMaskGroupWidget18.dart';
import 'package:flutterapp/boardgamesapp/generatedsearchwidget/generated/GeneratedMaskGroupWidget20.dart';
import 'package:flutterapp/boardgamesapp/generatedsearchwidget/generated/GeneratedMaskGroupWidget17.dart';

/* Frame Search
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSearchWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 40, 34, 34),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 31.0,
                child: GeneratedRectangle4Widget7(),
              ),
              Positioned(
                left: 17.0,
                top: 57.0,
                right: null,
                bottom: null,
                width: 341.0,
                height: 58.0,
                child: GeneratedMaskGroupWidget17(),
              ),
              Positioned(
                left: 17.0,
                top: 126.0,
                right: null,
                bottom: null,
                width: 341.0,
                height: 83.0,
                child: GeneratedMaskGroupWidget18(),
              ),
              Positioned(
                left: 17.0,
                top: 292.0,
                right: null,
                bottom: null,
                width: 341.0,
                height: 83.0,
                child: GeneratedMaskGroupWidget19(),
              ),
              Positioned(
                left: 17.0,
                top: 209.0,
                right: null,
                bottom: null,
                width: 341.0,
                height: 83.0,
                child: GeneratedMaskGroupWidget20(),
              )
            ]),
      ),
    ));
  }
}
