import 'package:flutter/material.dart';
import 'package:flutterapp/boardgamesapp/generatedloginwidget/generated/GeneratedBlancodadosriesgoarriesgadovectorilustracionarte_105631.dart';
import 'package:flutterapp/boardgamesapp/generatedloginwidget/generated/GeneratedIconocandado1Widget.dart';
import 'package:flutterapp/boardgamesapp/generatedloginwidget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/boardgamesapp/generatedloginwidget/generated/GeneratedLine4Widget.dart';
import 'package:flutterapp/boardgamesapp/generatedloginwidget/generated/GeneratedHasolvidadotucontraseaWidget.dart';
import 'package:flutterapp/boardgamesapp/generatedloginwidget/generated/GeneratedLine5Widget.dart';
import 'package:flutterapp/boardgamesapp/generatedloginwidget/generated/Generated585e4be1cb11b227491c33981Widget.dart';
import 'package:flutterapp/boardgamesapp/generatedloginwidget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/boardgamesapp/generatedloginwidget/generated/GeneratedArrow1Widget.dart';
import 'package:flutterapp/boardgamesapp/generatedloginwidget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/boardgamesapp/generatedloginwidget/generated/GeneratedLOGINWidget.dart';
import 'package:flutterapp/boardgamesapp/generatedloginwidget/generated/GeneratedRectangle1Widget.dart';

/* Frame Login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          border: Border.all(
            width: 1.0,
            color: Color.fromARGB(255, 0, 0, 0),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 70.0,
                top: 389.0,
                right: null,
                bottom: null,
                width: 235.0,
                height: 34.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 70.0,
                top: 434.0,
                right: null,
                bottom: null,
                width: 235.0,
                height: 34.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 89.0,
                top: 479.0,
                right: null,
                bottom: null,
                width: 197.0,
                height: 26.0,
                child: GeneratedRectangle3Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 31.0,
                child: GeneratedRectangle5Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 220.0,
                right: null,
                bottom: null,
                width: 333.0,
                height: 139.0,
                child:
                    GeneratedBlancodadosriesgoarriesgadovectorilustracionarte_105631(),
              ),
              Positioned(
                left: 375.0,
                top: 406.0,
                right: null,
                bottom: null,
                width: 268.0,
                height: 0.0,
                child: GeneratedArrow1Widget(),
              ),
              Positioned(
                left: 76.0,
                top: 391.0,
                right: null,
                bottom: null,
                width: 31.0,
                height: 30.0,
                child: Generated585e4be1cb11b227491c33981Widget(),
              ),
              Positioned(
                left: 113.0,
                top: 389.0,
                right: null,
                bottom: null,
                width: 34.0,
                height: 1.0,
                child: GeneratedLine4Widget(),
              ),
              Positioned(
                left: 113.0,
                top: 434.0,
                right: null,
                bottom: null,
                width: 34.0,
                height: 1.0,
                child: GeneratedLine5Widget(),
              ),
              Positioned(
                left: 76.0,
                top: 436.0,
                right: null,
                bottom: null,
                width: 29.0625,
                height: 31.0,
                child: GeneratedIconocandado1Widget(),
              ),
              Positioned(
                left: 171.0,
                top: 508.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 13.0,
                child: GeneratedHasolvidadotucontraseaWidget(),
              ),
              Positioned(
                left: 91.0,
                top: 487.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 17.0,
                child: GeneratedLOGINWidget(),
              )
            ]),
      ),
    ));
  }
}
