import 'package:flutter/material.dart';
import 'package:flutterapp/boardgamesapp/generatedpaginaprincipalwidget/generated/GeneratedUser2Widget.dart';
import 'package:flutterapp/boardgamesapp/generatedpaginaprincipalwidget/generated/GeneratedContrarytopopularbeliefLoremIpsumisnotsimplyrandomtextI2.dart';
import 'package:flutterapp/boardgamesapp/generatedpaginaprincipalwidget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/boardgamesapp/generatedpaginaprincipalwidget/generated/GeneratedFrame3Widget.dart';
import 'package:flutterapp/boardgamesapp/generatedpaginaprincipalwidget/generated/GeneratedBell1Widget.dart';
import 'package:flutterapp/boardgamesapp/generatedpaginaprincipalwidget/generated/GeneratedFrame1Widget.dart';
import 'package:flutterapp/boardgamesapp/generatedpaginaprincipalwidget/generated/GeneratedContrarytopopularbeliefLoremIpsumisnotsimplyrandomtextI.dart';
import 'package:flutterapp/boardgamesapp/generatedpaginaprincipalwidget/generated/GeneratedHouse1Widget.dart';
import 'package:flutterapp/boardgamesapp/generatedpaginaprincipalwidget/generated/GeneratedImagen_20210118_1634501Widget.dart';
import 'package:flutterapp/boardgamesapp/generatedpaginaprincipalwidget/generated/GeneratedHouse2Widget.dart';
import 'package:flutterapp/boardgamesapp/generatedpaginaprincipalwidget/generated/GeneratedNombrejuegoWidget2.dart';
import 'package:flutterapp/boardgamesapp/generatedpaginaprincipalwidget/generated/GeneratedFrame2Widget.dart';
import 'package:flutterapp/boardgamesapp/generatedpaginaprincipalwidget/generated/GeneratedUser1Widget.dart';
import 'package:flutterapp/boardgamesapp/generatedpaginaprincipalwidget/generated/GeneratedImagen_20210118_1634502Widget.dart';
import 'package:flutterapp/boardgamesapp/generatedpaginaprincipalwidget/generated/GeneratedNombrejuegoWidget1.dart';
import 'package:flutterapp/boardgamesapp/generatedpaginaprincipalwidget/generated/GeneratedLine4Widget1.dart';
import 'package:flutterapp/boardgamesapp/generatedpaginaprincipalwidget/generated/GeneratedMenu1Widget.dart';
import 'package:flutterapp/boardgamesapp/generatedpaginaprincipalwidget/generated/GeneratedBell2Widget.dart';
import 'package:flutterapp/boardgamesapp/generatedpaginaprincipalwidget/generated/GeneratedLine3Widget.dart';
import 'package:flutterapp/boardgamesapp/generatedpaginaprincipalwidget/generated/GeneratedContrarytopopularbeliefLoremIpsumisnotsimplyrandomtextI1.dart';
import 'package:flutterapp/boardgamesapp/generatedpaginaprincipalwidget/generated/GeneratedSearch1Widget.dart';
import 'package:flutterapp/boardgamesapp/generatedpaginaprincipalwidget/generated/GeneratedNombrejuegoWidget.dart';
import 'package:flutterapp/boardgamesapp/generatedpaginaprincipalwidget/generated/GeneratedLine1Widget.dart';
import 'package:flutterapp/boardgamesapp/generatedpaginaprincipalwidget/generated/GeneratedHOMEPAGEWidget.dart';

/* Frame Pagina Principal
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPaginaPrincipalWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedOpcionsWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 812.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 40, 34, 34),
                  ),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 31.0,
                  child: GeneratedRectangle4Widget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 740.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 1.0,
                  child: GeneratedLine1Widget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 95.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 1.0,
                  child: GeneratedLine3Widget(),
                ),
                Positioned(
                  left: 304.0,
                  top: 757.0,
                  right: null,
                  bottom: null,
                  width: 35.0,
                  height: 35.0,
                  child: GeneratedImagen_20210118_1634501Widget(),
                ),
                Positioned(
                  left: 122.0,
                  top: 757.0,
                  right: null,
                  bottom: null,
                  width: 35.0,
                  height: 35.0,
                  child: GeneratedBell1Widget(),
                ),
                Positioned(
                  left: 213.0,
                  top: 757.0,
                  right: null,
                  bottom: null,
                  width: 35.0,
                  height: 35.0,
                  child: GeneratedUser1Widget(),
                ),
                Positioned(
                  left: 31.0,
                  top: 757.0,
                  right: null,
                  bottom: null,
                  width: 35.0,
                  height: 35.0,
                  child: GeneratedHouse1Widget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 740.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 1.0,
                  child: GeneratedLine4Widget1(),
                ),
                Positioned(
                  left: 304.0,
                  top: 757.0,
                  right: null,
                  bottom: null,
                  width: 35.0,
                  height: 35.0,
                  child: GeneratedImagen_20210118_1634502Widget(),
                ),
                Positioned(
                  left: 122.0,
                  top: 757.0,
                  right: null,
                  bottom: null,
                  width: 35.0,
                  height: 35.0,
                  child: GeneratedBell2Widget(),
                ),
                Positioned(
                  left: 213.0,
                  top: 757.0,
                  right: null,
                  bottom: null,
                  width: 35.0,
                  height: 35.0,
                  child: GeneratedUser2Widget(),
                ),
                Positioned(
                  left: 31.0,
                  top: 757.0,
                  right: null,
                  bottom: null,
                  width: 35.0,
                  height: 35.0,
                  child: GeneratedHouse2Widget(),
                ),
                Positioned(
                  left: 304.0,
                  top: 46.0,
                  right: null,
                  bottom: null,
                  width: 35.0,
                  height: 35.0,
                  child: GeneratedSearch1Widget(),
                ),
                Positioned(
                  left: 31.0,
                  top: 46.0,
                  right: null,
                  bottom: null,
                  width: 35.0,
                  height: 35.0,
                  child: GeneratedMenu1Widget(),
                ),
                Positioned(
                  left: 17.0,
                  top: 110.0,
                  right: null,
                  bottom: null,
                  width: 342.0,
                  height: 152.0,
                  child: GeneratedFrame1Widget(),
                ),
                Positioned(
                  left: 148.0,
                  top: 163.0,
                  right: null,
                  bottom: null,
                  width: 201.0,
                  height: 76.0,
                  child:
                      GeneratedContrarytopopularbeliefLoremIpsumisnotsimplyrandomtextI(),
                ),
                Positioned(
                  left: 148.0,
                  top: 122.0,
                  right: null,
                  bottom: null,
                  width: 201.0,
                  height: 26.0,
                  child: GeneratedNombrejuegoWidget(),
                ),
                Positioned(
                  left: 17.0,
                  top: 279.0,
                  right: null,
                  bottom: null,
                  width: 342.0,
                  height: 152.0,
                  child: GeneratedFrame2Widget(),
                ),
                Positioned(
                  left: 148.0,
                  top: 332.0,
                  right: null,
                  bottom: null,
                  width: 201.0,
                  height: 76.0,
                  child:
                      GeneratedContrarytopopularbeliefLoremIpsumisnotsimplyrandomtextI1(),
                ),
                Positioned(
                  left: 148.0,
                  top: 291.0,
                  right: null,
                  bottom: null,
                  width: 201.0,
                  height: 26.0,
                  child: GeneratedNombrejuegoWidget1(),
                ),
                Positioned(
                  left: 17.0,
                  top: 448.0,
                  right: null,
                  bottom: null,
                  width: 342.0,
                  height: 152.0,
                  child: GeneratedFrame3Widget(),
                ),
                Positioned(
                  left: 148.0,
                  top: 501.0,
                  right: null,
                  bottom: null,
                  width: 201.0,
                  height: 76.0,
                  child:
                      GeneratedContrarytopopularbeliefLoremIpsumisnotsimplyrandomtextI2(),
                ),
                Positioned(
                  left: 148.0,
                  top: 460.0,
                  right: null,
                  bottom: null,
                  width: 201.0,
                  height: 26.0,
                  child: GeneratedNombrejuegoWidget2(),
                ),
                Positioned(
                  left: 115.0,
                  top: 52.0,
                  right: null,
                  bottom: null,
                  width: 161.0,
                  height: 22.0,
                  child: GeneratedHOMEPAGEWidget(),
                )
              ]),
        ),
      ),
    ));
  }
}
