import 'package:flutter/material.dart';
import 'package:flutterapp/boardgamesapp/generatedsettingswidget/generated/GeneratedPngtransparentcomputericonselectricalswitchessliderbutt.dart';
import 'package:flutterapp/boardgamesapp/generatedsettingswidget/generated/GeneratedCaretdown3Widget.dart';
import 'package:flutterapp/boardgamesapp/generatedsettingswidget/generated/GeneratedUser4Widget.dart';
import 'package:flutterapp/boardgamesapp/generatedsettingswidget/generated/GeneratedHouse3Widget.dart';
import 'package:flutterapp/boardgamesapp/generatedsettingswidget/generated/GeneratedSettingsWidget1.dart';
import 'package:flutterapp/boardgamesapp/generatedsettingswidget/generated/GeneratedUser3Widget.dart';
import 'package:flutterapp/boardgamesapp/generatedsettingswidget/generated/GeneratedCaretdown2Widget.dart';
import 'package:flutterapp/boardgamesapp/generatedsettingswidget/generated/GeneratedNotificationsWidget.dart';
import 'package:flutterapp/boardgamesapp/generatedsettingswidget/generated/GeneratedImagen_20210118_1634504Widget.dart';
import 'package:flutterapp/boardgamesapp/generatedsettingswidget/generated/GeneratedLogoutWidget.dart';
import 'package:flutterapp/boardgamesapp/generatedsettingswidget/generated/GeneratedLanguageWidget.dart';
import 'package:flutterapp/boardgamesapp/generatedsettingswidget/generated/GeneratedImagen_20210118_1634503Widget.dart';
import 'package:flutterapp/boardgamesapp/generatedsettingswidget/generated/GeneratedHouse4Widget.dart';
import 'package:flutterapp/boardgamesapp/generatedsettingswidget/generated/GeneratedBell3Widget.dart';
import 'package:flutterapp/boardgamesapp/generatedsettingswidget/generated/GeneratedLine6Widget.dart';
import 'package:flutterapp/boardgamesapp/generatedsettingswidget/generated/GeneratedLine5Widget2.dart';
import 'package:flutterapp/boardgamesapp/generatedsettingswidget/generated/GeneratedInformationWidget.dart';
import 'package:flutterapp/boardgamesapp/generatedsettingswidget/generated/GeneratedRectangle4Widget2.dart';
import 'package:flutterapp/boardgamesapp/generatedsettingswidget/generated/GeneratedLanguage1Widget.dart';
import 'package:flutterapp/boardgamesapp/generatedsettingswidget/generated/GeneratedPngtransparentcomputericonselectricalswitchessliderbutt1.dart';
import 'package:flutterapp/boardgamesapp/generatedsettingswidget/generated/GeneratedLine7Widget.dart';
import 'package:flutterapp/boardgamesapp/generatedsettingswidget/generated/GeneratedDarkthemeWidget.dart';
import 'package:flutterapp/boardgamesapp/generatedsettingswidget/generated/GeneratedInfo1Widget.dart';
import 'package:flutterapp/boardgamesapp/generatedsettingswidget/generated/GeneratedBell4Widget.dart';
import 'package:flutterapp/boardgamesapp/generatedsettingswidget/generated/GeneratedMoonpng1Widget.dart';
import 'package:flutterapp/boardgamesapp/generatedsettingswidget/generated/GeneratedCb8ffe58e3402453d5d9030acc5766ad1Widget.dart';

/* Frame Settings
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSettingsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedPaginaPrincipalWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 812.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 40, 34, 34),
                  ),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 31.0,
                  child: GeneratedRectangle4Widget2(),
                ),
                Positioned(
                  left: 31.0,
                  top: 48.0,
                  right: null,
                  bottom: null,
                  width: 147.0,
                  height: 57.0,
                  child: GeneratedSettingsWidget1(),
                ),
                Positioned(
                  left: 0.0,
                  top: 742.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 1.0,
                  child: GeneratedLine5Widget2(),
                ),
                Positioned(
                  left: 304.0,
                  top: 759.0,
                  right: null,
                  bottom: null,
                  width: 35.0,
                  height: 35.0,
                  child: GeneratedImagen_20210118_1634503Widget(),
                ),
                Positioned(
                  left: 122.0,
                  top: 759.0,
                  right: null,
                  bottom: null,
                  width: 35.0,
                  height: 35.0,
                  child: GeneratedBell3Widget(),
                ),
                Positioned(
                  left: 213.0,
                  top: 759.0,
                  right: null,
                  bottom: null,
                  width: 35.0,
                  height: 35.0,
                  child: GeneratedUser3Widget(),
                ),
                Positioned(
                  left: 31.0,
                  top: 759.0,
                  right: null,
                  bottom: null,
                  width: 35.0,
                  height: 35.0,
                  child: GeneratedHouse3Widget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 742.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 1.0,
                  child: GeneratedLine6Widget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 112.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 1.0,
                  child: GeneratedLine7Widget(),
                ),
                Positioned(
                  left: 304.0,
                  top: 759.0,
                  right: null,
                  bottom: null,
                  width: 35.0,
                  height: 35.0,
                  child: GeneratedImagen_20210118_1634504Widget(),
                ),
                Positioned(
                  left: 122.0,
                  top: 759.0,
                  right: null,
                  bottom: null,
                  width: 35.0,
                  height: 35.0,
                  child: GeneratedBell4Widget(),
                ),
                Positioned(
                  left: 213.0,
                  top: 759.0,
                  right: null,
                  bottom: null,
                  width: 35.0,
                  height: 35.0,
                  child: GeneratedUser4Widget(),
                ),
                Positioned(
                  left: 31.0,
                  top: 759.0,
                  right: null,
                  bottom: null,
                  width: 35.0,
                  height: 35.0,
                  child: GeneratedHouse4Widget(),
                ),
                Positioned(
                  left: 69.0,
                  top: 125.0,
                  right: null,
                  bottom: null,
                  width: 308.0,
                  height: 50.0,
                  child: GeneratedDarkthemeWidget(),
                ),
                Positioned(
                  left: 69.0,
                  top: 177.0,
                  right: null,
                  bottom: null,
                  width: 311.0,
                  height: 53.0,
                  child: GeneratedLanguageWidget(),
                ),
                Positioned(
                  left: 69.0,
                  top: 228.0,
                  right: null,
                  bottom: null,
                  width: 311.0,
                  height: 53.0,
                  child: GeneratedNotificationsWidget(),
                ),
                Positioned(
                  left: 69.0,
                  top: 281.0,
                  right: null,
                  bottom: null,
                  width: 311.0,
                  height: 53.0,
                  child: GeneratedInformationWidget(),
                ),
                Positioned(
                  left: 31.0,
                  top: 138.0,
                  right: null,
                  bottom: null,
                  width: 20.0,
                  height: 22.0,
                  child: GeneratedMoonpng1Widget(),
                ),
                Positioned(
                  left: 279.0,
                  top: 141.0,
                  right: null,
                  bottom: null,
                  width: 54.0,
                  height: 27.0,
                  child:
                      GeneratedPngtransparentcomputericonselectricalswitchessliderbutt(),
                ),
                Positioned(
                  left: 279.0,
                  top: 237.0,
                  right: null,
                  bottom: null,
                  width: 54.0,
                  height: 27.0,
                  child:
                      GeneratedPngtransparentcomputericonselectricalswitchessliderbutt1(),
                ),
                Positioned(
                  left: 308.0,
                  top: 292.0,
                  right: null,
                  bottom: null,
                  width: 25.0,
                  height: 26.0,
                  child: GeneratedCaretdown2Widget(),
                ),
                Positioned(
                  left: 308.0,
                  top: 188.0,
                  right: null,
                  bottom: null,
                  width: 25.0,
                  height: 26.0,
                  child: GeneratedCaretdown3Widget(),
                ),
                Positioned(
                  left: 31.0,
                  top: 191.0,
                  right: null,
                  bottom: null,
                  width: 21.0,
                  height: 21.0,
                  child: GeneratedLanguage1Widget(),
                ),
                Positioned(
                  left: 22.0,
                  top: 239.0,
                  right: null,
                  bottom: null,
                  width: 38.0,
                  height: 27.0,
                  child: GeneratedCb8ffe58e3402453d5d9030acc5766ad1Widget(),
                ),
                Positioned(
                  left: 26.0,
                  top: 292.0,
                  right: null,
                  bottom: null,
                  width: 29.0,
                  height: 26.0,
                  child: GeneratedInfo1Widget(),
                ),
                Positioned(
                  left: 281.0,
                  top: 687.0,
                  right: null,
                  bottom: null,
                  width: 96.0,
                  height: 42.0,
                  child: GeneratedLogoutWidget(),
                )
              ]),
        ),
      ),
    ));
  }
}
