import 'package:flutter/material.dart';
import 'package:flutterapp/boardgamesapp/generatedreviewpublicadawidget/generated/GeneratedRectangle4Widget6.dart';
import 'package:flutterapp/boardgamesapp/generatedreviewpublicadawidget/generated/GeneratedMaskGroupWidget14.dart';
import 'package:flutterapp/boardgamesapp/generatedreviewpublicadawidget/generated/GeneratedMaskGroupWidget15.dart';
import 'package:flutterapp/boardgamesapp/generatedreviewpublicadawidget/generated/GeneratedNombrejuegoWidget10.dart';
import 'package:flutterapp/boardgamesapp/generatedreviewpublicadawidget/generated/GeneratedBynombreuserWidget.dart';
import 'package:flutterapp/boardgamesapp/generatedreviewpublicadawidget/generated/GeneratedMaskGroupWidget16.dart';
import 'package:flutterapp/boardgamesapp/generatedreviewpublicadawidget/generated/GeneratedCaretdown4Widget1.dart';
import 'package:flutterapp/boardgamesapp/generatedreviewpublicadawidget/generated/GeneratedLine2Widget.dart';
import 'package:flutterapp/boardgamesapp/generatedreviewpublicadawidget/generated/GeneratedImagen_20210118_1634502Widget1.dart';
import 'package:flutterapp/boardgamesapp/generatedreviewpublicadawidget/generated/GeneratedUser2Widget1.dart';
import 'package:flutterapp/boardgamesapp/generatedreviewpublicadawidget/generated/GeneratedMaskGroupWidget13.dart';
import 'package:flutterapp/boardgamesapp/generatedreviewpublicadawidget/generated/GeneratedBell2Widget1.dart';
import 'package:flutterapp/boardgamesapp/generatedreviewpublicadawidget/generated/GeneratedCaretdown2Widget1.dart';
import 'package:flutterapp/boardgamesapp/generatedreviewpublicadawidget/generated/GeneratedHouse2Widget1.dart';
import 'package:flutterapp/boardgamesapp/generatedreviewpublicadawidget/generated/GeneratedCaretdown4Widget.dart';

/* Frame Review Publicada
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedReviewPublicadaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 40, 34, 34),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 31.0,
                child: GeneratedRectangle4Widget6(),
              ),
              Positioned(
                left: 28.0,
                top: 194.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 212.0,
                child: GeneratedMaskGroupWidget13(),
              ),
              Positioned(
                left: 25.0,
                top: 133.0,
                right: null,
                bottom: null,
                width: 258.0,
                height: 50.0,
                child: GeneratedMaskGroupWidget14(),
              ),
              Positioned(
                left: 25.0,
                top: 42.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedMaskGroupWidget15(),
              ),
              Positioned(
                left: 25.0,
                top: 92.0,
                right: null,
                bottom: null,
                width: 201.0,
                height: 26.0,
                child: GeneratedNombrejuegoWidget10(),
              ),
              Positioned(
                left: 198.0,
                top: 406.0,
                right: null,
                bottom: null,
                width: 151.0,
                height: 26.0,
                child: GeneratedBynombreuserWidget(),
              ),
              Positioned(
                left: 61.0,
                top: 472.0,
                right: null,
                bottom: null,
                width: 253.0,
                height: 218.0,
                child: GeneratedMaskGroupWidget16(),
              ),
              Positioned(
                left: 322.0,
                top: 568.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 26.0,
                child: GeneratedCaretdown4Widget(),
              ),
              Positioned(
                left: 308.0,
                top: 292.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 26.0,
                child: GeneratedCaretdown2Widget1(),
              ),
              Positioned(
                left: 53.0,
                top: 594.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 26.0,
                child: GeneratedCaretdown4Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 746.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedLine2Widget(),
              ),
              Positioned(
                left: 304.0,
                top: 763.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedImagen_20210118_1634502Widget1(),
              ),
              Positioned(
                left: 122.0,
                top: 763.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedBell2Widget1(),
              ),
              Positioned(
                left: 213.0,
                top: 763.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedUser2Widget1(),
              ),
              Positioned(
                left: 31.0,
                top: 763.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedHouse2Widget1(),
              )
            ]),
      ),
    ));
  }
}
