import 'package:flutter/material.dart';
import 'package:flutterapp/boardgamesapp/generateduserpagewidget/generated/GeneratedBell1Widget1.dart';
import 'package:flutterapp/boardgamesapp/generateduserpagewidget/generated/GeneratedLine7Widget1.dart';
import 'package:flutterapp/boardgamesapp/generateduserpagewidget/generated/GeneratedLine6Widget1.dart';
import 'package:flutterapp/boardgamesapp/generateduserpagewidget/generated/GeneratedImagen_20210118_1634501Widget1.dart';
import 'package:flutterapp/boardgamesapp/generateduserpagewidget/generated/GeneratedFrame5Widget.dart';
import 'package:flutterapp/boardgamesapp/generateduserpagewidget/generated/GeneratedStar1Widget.dart';
import 'package:flutterapp/boardgamesapp/generateduserpagewidget/generated/GeneratedLine1Widget1.dart';
import 'package:flutterapp/boardgamesapp/generateduserpagewidget/generated/GeneratedContrarytopopularbeliefLoremIpsumisnotsimplyrandomtextI4.dart';
import 'package:flutterapp/boardgamesapp/generateduserpagewidget/generated/GeneratedLine8Widget.dart';
import 'package:flutterapp/boardgamesapp/generateduserpagewidget/generated/GeneratedUser1Widget1.dart';
import 'package:flutterapp/boardgamesapp/generateduserpagewidget/generated/GeneratedUserimagewithblackbackground1Widget.dart';
import 'package:flutterapp/boardgamesapp/generateduserpagewidget/generated/GeneratedFrame4Widget.dart';
import 'package:flutterapp/boardgamesapp/generateduserpagewidget/generated/GeneratedContrarytopopularbeliefLoremIpsumisnotsimplyrandomtextI3.dart';
import 'package:flutterapp/boardgamesapp/generateduserpagewidget/generated/GeneratedRectangle4Widget3.dart';
import 'package:flutterapp/boardgamesapp/generateduserpagewidget/generated/GeneratedNombrejuegoWidget4.dart';
import 'package:flutterapp/boardgamesapp/generateduserpagewidget/generated/GeneratedLine9Widget.dart';
import 'package:flutterapp/boardgamesapp/generateduserpagewidget/generated/GeneratedLine10Widget.dart';
import 'package:flutterapp/boardgamesapp/generateduserpagewidget/generated/GeneratedRectangle8Widget.dart';
import 'package:flutterapp/boardgamesapp/generateduserpagewidget/generated/GeneratedEllipse8Widget.dart';
import 'package:flutterapp/boardgamesapp/generateduserpagewidget/generated/GeneratedNombrejuegoWidget3.dart';
import 'package:flutterapp/boardgamesapp/generateduserpagewidget/generated/GeneratedHouse1Widget1.dart';
import 'package:flutterapp/boardgamesapp/generateduserpagewidget/generated/GeneratedFrame3Widget1.dart';

/* Frame UserPage
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUserPageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 40, 34, 34),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 31.0,
                child: GeneratedRectangle4Widget3(),
              ),
              Positioned(
                left: -2.842170943040401e-14,
                top: 200.0,
                right: null,
                bottom: null,
                width: 374.99603271484375,
                height: 5.0,
                child: GeneratedLine6Widget1(),
              ),
              Positioned(
                left: 121.0,
                top: 94.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 133.0,
                child: GeneratedEllipse8Widget(),
              ),
              Positioned(
                left: 121.0,
                top: 82.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 137.0,
                child: GeneratedUserimagewithblackbackground1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 260.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 51.0,
                child: GeneratedRectangle8Widget(),
              ),
              Positioned(
                left: 121.0,
                top: 260.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 2.0,
                child: GeneratedLine7Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 311.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 3.0,
                child: GeneratedLine9Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 260.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 3.0,
                child: GeneratedLine10Widget(),
              ),
              Positioned(
                left: 254.0,
                top: 260.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 2.0,
                child: GeneratedLine8Widget(),
              ),
              Positioned(
                left: 17.0,
                top: 330.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 152.0,
                child: GeneratedFrame3Widget1(),
              ),
              Positioned(
                left: 148.0,
                top: 383.0,
                right: null,
                bottom: null,
                width: 201.0,
                height: 76.0,
                child:
                    GeneratedContrarytopopularbeliefLoremIpsumisnotsimplyrandomtextI3(),
              ),
              Positioned(
                left: 148.0,
                top: 342.0,
                right: null,
                bottom: null,
                width: 201.0,
                height: 26.0,
                child: GeneratedNombrejuegoWidget3(),
              ),
              Positioned(
                left: 17.0,
                top: 500.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 152.0,
                child: GeneratedFrame4Widget(),
              ),
              Positioned(
                left: 17.0,
                top: 500.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 152.0,
                child: GeneratedFrame5Widget(),
              ),
              Positioned(
                left: 148.0,
                top: 553.0,
                right: null,
                bottom: null,
                width: 201.0,
                height: 76.0,
                child:
                    GeneratedContrarytopopularbeliefLoremIpsumisnotsimplyrandomtextI4(),
              ),
              Positioned(
                left: 148.0,
                top: 512.0,
                right: null,
                bottom: null,
                width: 201.0,
                height: 26.0,
                child: GeneratedNombrejuegoWidget4(),
              ),
              Positioned(
                left: 43.0,
                top: 267.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedStar1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 740.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedLine1Widget1(),
              ),
              Positioned(
                left: 304.0,
                top: 757.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedImagen_20210118_1634501Widget1(),
              ),
              Positioned(
                left: 122.0,
                top: 757.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedBell1Widget1(),
              ),
              Positioned(
                left: 213.0,
                top: 757.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedUser1Widget1(),
              ),
              Positioned(
                left: 31.0,
                top: 757.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedHouse1Widget1(),
              )
            ]),
      ),
    ));
  }
}
